ClientManagementHomework/Models/客戶銀行資訊.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManagementHomework.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class 客戶銀行資訊
    {
        public int Id { get; set; }
        public int 客戶Id { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "字串長度不可超過50字")]
        public string 銀行名稱 { get; set; }
        [Required]
        public int 銀行代碼 { get; set; }
        public Nullable<int> 分行代碼 { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "字串長度不可超過50字")]
        public string 帳戶名稱 { get; set; }
        [Required]
        [StringLength(20, ErrorMessage = "字串長度不可超過20字")]
        public string 帳戶號碼 { get; set; }
        public bool 已刪除 { get; set; }
    
        public virtual 客戶資料 客戶資料 { get; set; }
    }
}

ClientManagementHomework/Controllers/客戶銀行資訊Controller.cs
using ClientManagementHomework.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ClientManagementHomework.Controllers
{
    public class 客戶銀行資訊Controller : Controller
    {
        private 客戶資料Entities db = new 客戶資料Entities();

        // GET: 客戶銀行資訊/Create
        public ActionResult Create()
        {
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱");
            return View();
        }

        // POST: 客戶銀行資訊/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶Id,銀行名稱,銀行代碼,分行代碼,帳戶名稱,帳戶號碼,已刪除")] 客戶銀行資訊 客戶銀行資訊)
        {
            if (ModelState.IsValid)
            {
                db.客戶銀行資訊.Add(客戶銀行資訊);
                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (DbEntityValidationResult item in ex.EntityValidationErrors)
                    {
                        foreach (var li in item.ValidationErrors)
                        {
                            throw new Exception(li.ErrorMessage);
                        }
                    }
                }
                return RedirectToAction("Index");
            }

            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        // GET: 客戶銀行資訊/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶銀行資訊 客戶銀行資訊 = db.客戶銀行資訊.Find(id);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            return View(客戶銀行資訊);
        }

        public ActionResult DeleteAll(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            foreach (var item in db.客戶銀行資訊.Where(x => x.已刪除.Equals(false) && x.客戶Id.Equals(id.Value)).ToList())
            {
                item.已刪除 = true;
            }
            db.SaveChanges();
            return RedirectToAction("Details", "客戶資料", new { id = id.Value });
        }

        // POST: 客戶銀行資訊/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            客戶銀行資訊 客戶銀行資訊 = db.客戶銀行資訊.Find(id);
            客戶銀行資訊.已刪除 = true;
            if (ModelState.IsValid)
            {
                //db.Entry(客戶銀行資訊).State = EntityState.Modified;
                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (DbEntityValidationResult item in ex.EntityValidationErrors)
                    {
                        foreach (var li in item.ValidationErrors)
                        {
                            throw new Exception(li.ErrorMessage);
                        }
                    }
                }
            }
            return RedirectToAction("Index");
        }

        // GET: 客戶銀行資訊/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶銀行資訊 客戶銀行資訊 = db.客戶銀行資訊.Find(id);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            return View(客戶銀行資訊);
        }

        // GET: 客戶銀行資訊/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶銀行資訊 客戶銀行資訊 = db.客戶銀行資訊.Find(id);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        // POST: 客戶銀行資訊/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶Id,銀行名稱,銀行代碼,分行代碼,帳戶名稱,帳戶號碼,已刪除")] 客戶銀行資訊 客戶銀行資訊)
        {
            if (ModelState.IsValid)
            {
                db.Entry(客戶銀行資訊).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        // GET: 客戶銀行資訊
        [HttpGet]
        public ActionResult Index(int? id)
        {
            var 客戶銀行資訊 = db.客戶銀行資訊.ToList().AsQueryable().Where(x => x.已刪除.Equals(false));
            if (id != null)
                客戶銀行資訊 = 客戶銀行資訊.Where(x => x.客戶Id.Equals(id));
            return View(客戶銀行資訊.ToList());
        }

        [HttpPost]
        public ActionResult Index(客戶銀行資訊 銀行資訊)
        {
            var result = db.客戶銀行資訊.Where(x => x.已刪除.Equals(false)).AsQueryable();
            if (銀行資訊.分行代碼 != null)
                result = result.Where(x => x.分行代碼 == 銀行資訊.分行代碼);
            if (!string.IsNullOrWhiteSpace(銀行資訊.帳戶名稱))
                result = result.Where(x => x.帳戶名稱 == 銀行資訊.帳戶名稱);
            if (!string.IsNullOrWhiteSpace(銀行資訊.帳戶號碼))
                result = result.Where(x => x.帳戶號碼 == 銀行資訊.帳戶號碼);
            if (銀行資訊.銀行代碼 != 0)
                result = result.Where(x => x.銀行代碼 == 銀行資訊.銀行代碼);
            if (!string.IsNullOrWhiteSpace(銀行資訊.銀行名稱))
                result = result.Where(x => x.銀行名稱 == 銀行資訊.銀行名稱);

            return View(result.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClientManagementHomework/Views/客戶銀行資訊/Create.cshtml
@model ClientManagementHomework.Models.客戶銀行資訊

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>客戶銀行資訊</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.分行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.分行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.分行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶號碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶號碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶號碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClientManagementHomework/Views/客戶銀行資訊/Delete.cshtml
@model ClientManagementHomework.Models.客戶銀行資訊

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>客戶銀行資訊</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.銀行名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.銀行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.分行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.分行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶號碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶號碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ClientManagementHomework/Views/客戶銀行資訊/Details.cshtml
@model ClientManagementHomework.Models.客戶銀行資訊

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>客戶銀行資訊</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.銀行名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.銀行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.分行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.分行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶號碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶號碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ClientManagementHomework/Views/客戶銀行資訊/Edit.cshtml
@model ClientManagementHomework.Models.客戶銀行資訊

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶銀行資訊</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.銀行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.分行代碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.分行代碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.分行代碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶號碼, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶號碼, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.帳戶號碼, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.已刪除, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.已刪除)
                    @Html.ValidationMessageFor(model => model.已刪除, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClientManagementHomework/Views/客戶銀行資訊/Index.cshtml
@model IEnumerable<ClientManagementHomework.Models.客戶銀行資訊>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("新增客戶銀行資訊", "Create", null, new { @class = "btn btn-primary" })
</p>

@using (Html.BeginForm("Index", "客戶銀行資訊"))
{
    <div class="form-group">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    @Html.DisplayNameFor(model => model.銀行名稱)
                    @Html.TextBox("銀行名稱", null, new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    @Html.DisplayNameFor(model => model.銀行代碼)
                    @Html.TextBox("銀行代碼", null, new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    @Html.DisplayNameFor(model => model.分行代碼)
                    @Html.TextBox("分行代碼", null, new { @class = "form-control" })
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    @Html.DisplayNameFor(model => model.帳戶名稱)
                    @Html.TextBox("帳戶名稱", null, new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    @Html.DisplayNameFor(model => model.帳戶號碼)
                    @Html.TextBox("帳戶號碼", null, new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                </div>
                <div class="col-md-3">
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.銀行名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.銀行代碼)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.分行代碼)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.帳戶名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.帳戶號碼)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.銀行名稱)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.銀行代碼)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.分行代碼)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.帳戶名稱)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.帳戶號碼)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.客戶資料.客戶名稱)
            </td>
            <td>
                @Html.ActionLink("編輯", "Edit", new { id = item.Id }) |
                @Html.ActionLink("查詢明細", "Details", new { id = item.Id }) |
                @Html.ActionLink("刪除", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>