ClientManagementHomework/Models/客戶資料.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManagementHomework.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class 客戶資料
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 客戶資料()
        {
            this.客戶銀行資訊 = new HashSet<客戶銀行資訊>();
            this.客戶聯絡人 = new HashSet<客戶聯絡人>();
        }

        public int Id { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "長度不可超過50個字")]
        public string 客戶名稱 { get; set; }
        [Required]
        [StringLength(8, ErrorMessage = "長度不可超過8個字")]
        public string 統一編號 { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "長度不可超過50個字")]
        public string 電話 { get; set; }
        [StringLength(50, ErrorMessage = "長度不可超過50個字")]
        public string 傳真 { get; set; }
        [StringLength(100, ErrorMessage = "長度不可超過100個字")]
        public string 地址 { get; set; }
        [StringLength(250, ErrorMessage = "長度不可超過250個字")]
        public string Email { get; set; }
        public bool 已刪除 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶銀行資訊> 客戶銀行資訊 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶聯絡人> 客戶聯絡人 { get; set; }
    }
}

ClientManagementHomework/Controllers/客戶聯絡人Controller.cs
using ClientManagementHomework.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ClientManagementHomework.Controllers
{
    public class 客戶聯絡人Controller : Controller
    {
        private 客戶資料Entities db = new 客戶資料Entities();

        // GET: 客戶聯絡人/Create
        public ActionResult Create()
        {
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱");
            return View();
        }

        // POST: 客戶聯絡人/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶Id,職稱,姓名,Email,手機,電話,已刪除")] 客戶聯絡人 客戶聯絡人)
        {
            if (ModelState.IsValid)
            {
                db.客戶聯絡人.Add(客戶聯絡人);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // GET: 客戶聯絡人/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = db.客戶聯絡人.Find(id);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            return View(客戶聯絡人);
        }

        public ActionResult DeleteAll(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            foreach (var item in db.客戶聯絡人.Where(x => x.已刪除.Equals(false) && x.客戶Id.Equals(id.Value)).ToList())
            {
                item.已刪除 = true;
            }
            db.SaveChanges();
            return RedirectToAction("Details", "客戶資料", new { id = id.Value });
        }

        // POST: 客戶聯絡人/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            客戶聯絡人 客戶聯絡人 = db.客戶聯絡人.Find(id);
            客戶聯絡人.已刪除 = true;
            if (ModelState.IsValid)
            {
                db.Entry(客戶聯絡人).State = EntityState.Modified;
                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (DbEntityValidationResult item in ex.EntityValidationErrors)
                    {
                        foreach (var li in item.ValidationErrors)
                        {
                            throw new Exception(li.ErrorMessage);
                        }
                    }
                }
            }
            return RedirectToAction("Index");
        }

        // GET: 客戶聯絡人/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = db.客戶聯絡人.Find(id);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            return View(客戶聯絡人);
        }

        // GET: 客戶聯絡人/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = db.客戶聯絡人.Find(id);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // POST: 客戶聯絡人/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶Id,職稱,姓名,Email,手機,電話,已刪除")] 客戶聯絡人 客戶聯絡人)
        {
            if (ModelState.IsValid)
            {
                db.Entry(客戶聯絡人).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // GET: 客戶聯絡人
        [HttpGet]
        public ActionResult Index(int? id)
        {
            var result = db.客戶聯絡人.ToList().AsQueryable().Where(x => x.已刪除.Equals(false));
            if (id == null)
            {
                //var 客戶聯絡人 = db.客戶聯絡人.Include(客 => 客.客戶資料);
            }
            else
            {
                result = result.Where(x => x.客戶Id == id);
            }
            return View(result.ToList());
        }

        [HttpPost]
        public ActionResult Index(客戶聯絡人 聯絡人)
        {
            var result = db.客戶聯絡人.ToList().AsQueryable().Where(x => x.已刪除.Equals(false));
            if (!string.IsNullOrWhiteSpace(聯絡人.姓名))
                result = result.Where(x => x.姓名.Equals(聯絡人.姓名));
            if (!string.IsNullOrWhiteSpace(聯絡人.職稱))
                result = result.Where(x => x.職稱.Equals(聯絡人.職稱));
            if (!string.IsNullOrWhiteSpace(聯絡人.手機))
                result = result.Where(x => x.手機.Equals(聯絡人.手機));
            if (!string.IsNullOrWhiteSpace(聯絡人.電話))
                result = result.Where(x => x.手機.Equals(聯絡人.電話));
            if (!string.IsNullOrWhiteSpace(聯絡人.Email))
                result = result.Where(x => x.手機.Equals(聯絡人.Email));
            return View(result.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClientManagementHomework/Controllers/客戶資料Controller.cs
using ClientManagementHomework.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ClientManagementHomework.Controllers
{
    public class 客戶資料Controller : Controller
    {
        private 客戶資料Entities db = new 客戶資料Entities();

        // GET: 客戶資料/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: 客戶資料/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶名稱,統一編號,電話,傳真,地址,Email")] 客戶資料 客戶資料)
        {
            if (ModelState.IsValid)
            {
                db.客戶資料.Add(客戶資料);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(客戶資料);
        }

        // GET: 客戶資料/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = db.客戶資料.Find(id);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // POST: 客戶資料/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (ModelState.IsValid)
            {
                客戶資料 客戶資料 = db.客戶資料.Find(id);
                客戶資料.已刪除 = true;

                //db.Entry(客戶資料).State = EntityState.Modified;

                foreach (var item in db.客戶聯絡人.Where(x => x.客戶Id == id).ToList())
                {
                    item.已刪除 = true;
                }

                foreach (var item in db.客戶銀行資訊.Where(x => x.客戶Id == id).ToList())
                {
                    item.已刪除 = true;
                }

                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (DbEntityValidationResult item in ex.EntityValidationErrors)
                    {
                        foreach (var li in item.ValidationErrors)
                        {
                            throw new Exception(li.ErrorMessage);
                        }
                    }
                }
                return RedirectToAction("Index");
            }

            /*客戶資料 客戶資料 = db.客戶資料.Find(id);
            db.客戶資料.Remove(客戶資料);
            db.SaveChanges();*/
            return RedirectToAction("Index");
        }

        // GET: 客戶資料/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = db.客戶資料.Find(id);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // GET: 客戶資料/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = db.客戶資料.Find(id);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // POST: 客戶資料/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶名稱,統一編號,電話,傳真,地址,Email")] 客戶資料 客戶資料)
        {
            if (ModelState.IsValid)
            {
                db.Entry(客戶資料).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(客戶資料);
        }

        // GET: 客戶資料
        public ActionResult Index(客戶資料 客戶資料)
        {
            var result = db.客戶資料.ToList().AsQueryable().Where(x => x.已刪除.Equals(false));
            if (!string.IsNullOrWhiteSpace(客戶資料.Email))
                result = result.Where(x => x.Email.Equals(客戶資料.Email));

            if (!string.IsNullOrWhiteSpace(客戶資料.傳真))
                result = result.Where(x => x.傳真.Equals(客戶資料.傳真));

            if (!string.IsNullOrWhiteSpace(客戶資料.地址))
                result = result.Where(x => x.地址.Equals(客戶資料.地址));

            if (!string.IsNullOrWhiteSpace(客戶資料.統一編號))
                result = result.Where(x => x.統一編號.Equals(客戶資料.統一編號));

            if (!string.IsNullOrWhiteSpace(客戶資料.電話))
                result = result.Where(x => x.電話.Equals(客戶資料.電話));
            if (!string.IsNullOrWhiteSpace(客戶資料.客戶名稱))
                result = result.Where(x => x.客戶名稱.Equals(客戶資料.客戶名稱));

            return View(result);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClientManagementHomework/Views/客戶資料/Create.cshtml
@model ClientManagementHomework.Models.客戶資料

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶資料</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.客戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.統一編號, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.統一編號, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.統一編號, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.傳真, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.傳真, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.傳真, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.地址, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.地址, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.地址, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClientManagementHomework/Views/客戶資料/Delete.cshtml
@model ClientManagementHomework.Models.客戶資料

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>客戶資料</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ClientManagementHomework/Views/客戶資料/Details.cshtml
@model ClientManagementHomework.Models.客戶資料

@{
    ViewBag.Title = "Details";
}

<h2>客戶資料明細</h2>

<div>
    <ul class="nav nav-pills">
        <li role="presentation">
            @Html.ActionLink("回上一頁", "Index")
        </li>
        <li role="presentation">
            @Html.ActionLink("編輯客戶資料", "Edit", new { id = Model.Id })
        </li>
        <li role="presentation" class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                客戶聯絡人資訊<span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li>
                    @Html.ActionLink("新增", "Create", "客戶聯絡人", null, null)
                </li>
                <li>
                    @Html.ActionLink("查詢明細", "Index", "客戶聯絡人", new { id = Model.Id }, null)
                </li>
                <li>
                    @Html.ActionLink("刪除", "DeleteAll", "客戶聯絡人", new { id = Model.Id }, null)
                </li>
            </ul>
        </li>
        <li role="presentation" class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                客戶銀行資訊<span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li>
                    @Html.ActionLink("新增", "Create", "客戶銀行資訊", null, null)
                </li>
                <li>
                    @Html.ActionLink("查詢明細", "Index", "客戶銀行資訊", new { id = Model.Id }, null)
                </li>
                <li>
                    @Html.ActionLink("刪除", "DeleteAll", "客戶銀行資訊", new { id = Model.Id }, null)
                </li>
            </ul>
        </li>
    </ul>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>

ClientManagementHomework/Views/客戶資料/Edit.cshtml
@model ClientManagementHomework.Models.客戶資料

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶資料</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.客戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.統一編號, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.統一編號, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.統一編號, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.傳真, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.傳真, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.傳真, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.地址, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.地址, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.地址, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClientManagementHomework/Views/客戶資料/Index.cshtml
@model IEnumerable<ClientManagementHomework.Models.客戶資料>
@{
    ViewBag.Title = "首頁";
}

<h2>客戶資料首頁</h2>

<p>
    @*
        http://blog.miniasp.com/post/2012/09/30/ASPNET-MVC-common-pitfall-for-html-actionlink-helper-method.aspx
    *@
    @Html.ActionLink("新增客戶資料", "Create", null, new { @class = "btn btn-primary" })
</p>
@using (Html.BeginForm("Index", "客戶資料"))
{
    <div class="form-group">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    @Html.DisplayNameFor(model => model.客戶名稱)
                    @Html.TextBox("客戶名稱", null, new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    @Html.DisplayNameFor(model => model.統一編號)
                    @Html.TextBox("統一編號", null, new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    @Html.DisplayNameFor(model => model.電話)
                    @Html.TextBox("電話", null, new { @class = "form-control" })
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    @Html.DisplayNameFor(model => model.地址)
                    @Html.TextBox("地址", null, new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    @Html.DisplayNameFor(model => model.Email)
                    @Html.TextBox("Email", null, new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    @Html.DisplayNameFor(model => model.傳真)
                    @Html.TextBox("傳真", null, new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.統一編號)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.電話)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.傳真)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.地址)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.客戶名稱)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.統一編號)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.電話)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.傳真)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.地址)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("編輯", "Edit", new { id = item.Id }) |
                @Html.ActionLink("資料明細", "Details", new { id = item.Id }) |
                @Html.ActionLink("刪除", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>